### ISSUE TITLE
Images Not Loading

### ISSUE THREAD

**Issue by prosenjitjoy** [suvoooo/Learn-TensorFlow#2]
First of all, thank you for your amazing explanation along with the code. But the images you provided are not loading. So it's difficult to follow your explanation. Please update the notebook so that it will load the images.

**Comment by suvoooo** [comment]
Is it the Resnet notebook? I can update it when I will get free time, but for a more detailed explanation you can always check the Medium [post](https://towardsdatascience.com/understand-and-implement-resnet-50-with-tensorflow-2-0-1190b9b52691).

**Comment by suvoooo** [comment]
> First of all, thank you for your amazing explanation along with the code. But the images you provided are not loading. So it's difficult to follow your explanation. Please update the notebook so that it will load the images.

Is it the Resnet notebook? I can update it when I will get free time, but for a more detailed explanation you can always check the Medium [post](https://towardsdatascience.com/understand-and-implement-resnet-50-with-tensorflow-2-0-1190b9b52691).
